yuuoa

diff --git a/actions/render/action.yml b/actions/render/action.yml
--- a/actions/render/action.yml
+++ b/actions/render/action.yml
@@ -23,13 +23,13 @@ runs:
     - id: checkout
       shell: bash
       run: |
-        git clone --depth 1 ${{ inputs.repository_url }} -b ${{ inputs.source_branch }} project
+        git clone --depth 1 ${{ inputs.repository_url }} -b ${{ inputs.source_branch }} t3docsproject
 
     - id: jobfile
       shell: bash
       run: |
-        touch project/jobfile.json
-        cat << EOF > project/jobfile.json
+        touch t3docsproject/jobfile.json
+        cat << EOF > t3docsproject/jobfile.json
         {
             "Overrides_cfg": {
                 "general": {
@@ -45,15 +45,49 @@ runs:
     - id: render
       shell: bash
       run: |
-        mkdir -p project/RenderedDocumentation
+        mkdir -p t3docsproject/RenderedDocumentation
         docker run --rm --user=$(id -u):$(id -g) \
-          -v $(pwd)/project:/PROJECT:ro \
-          -v $(pwd)/project/RenderedDocumentation:/RESULT \
+          -v $(pwd)/t3docsproject:/t3docsproject:ro \
+          -v $(pwd)/t3docsproject/RenderedDocumentation:/RESULT \
           t3docs/render-documentation makehtml \
             -c make_singlehtml 1 \
-            -c "/ALL/Menu/mainmenu.sh makehtml -c replace_static_in_html 1 -c make_singlehtml 1 -c jobfile /PROJECT/jobfile.json"
+            -c "/ALL/Menu/mainmenu.sh makehtml -c replace_static_in_html 1 -c make_singlehtml 1 -c jobfile /t3docsproject/jobfile.json"
+
+
+    - id: langhandling
+      shell: bash
+      working-directory: t3docsproject
+      run: |
+        # test if rendering failed for whatever reason
+        ls RenderedDocumentation/Result || exit 1
+
+        # if a result has been rendered for the main directory, we treat that as the 'en_us' version
+        if [ -d RenderedDocumentation/Result/project/0.0.0/ ]; then
+                echo "Handling main doc result as en-us version"
+                mkdir FinalDocumentation/en-us
+                # Move en-us files to target dir, including dot files
+                (shopt -s dotglob; mv RenderedDocumentation/Result/project/0.0.0/* FinalDocumentation/en-us)
+                # Remove the directory, all content has been moved
+                rmdir RenderedDocumentation/Result/project/0.0.0/
+                # Remove a possibly existing Localization.en_us directory, if it exists
+                rm -rf RenderedDocumentation/Result/project/en-us/
+        fi
+
+        # now see if other localization versions have been rendered. if so, move them to FinalDocumentation/, too
+        if [ "$(ls -A RenderedDocumentation/Result/t3docsproject/)" ]; then
+            for LOCALIZATIONDIR in RenderedDocumentation/Result/t3docsproject/*; do
+                    LOCALIZATION=`basename $LOCALIZATIONDIR`
+                    echo "Handling localized documentation version ${LOCALIZATION:?Localization could not be determined}"
+                    mkdir FinalDocumentation/${LOCALIZATION}
+                    (shopt -s dotglob; mv ${LOCALIZATIONDIR}/0.0.0/* FinalDocumentation/${LOCALIZATION})
+                    # Remove the localization dir, it should be empty now
+                    rmdir ${LOCALIZATIONDIR}/0.0.0/
+                    rmdir ${LOCALIZATIONDIR}
+            done
+        fi
 
     - id: output
       shell: bash
       run: |
-        echo "::set-output name=renderedPath::project/RenderedDocumentation/Result/project/0.0.0"
+        rmdir t3docsproject/RenderedDocumentation
+        echo "::set-output name=renderedPath::t3docsproject/FinalDocumentation/"
